version: "3.5"
services:
  redis-server:
    image: "redis"
    restart: always
  count-app:
    image: "junius06/countup:latest"
    container_name: countup-green
    restart: unless-stopped
    ports:
      - "8889:8080"