name: Telegram Alert

# 워크플로우 cicd.yml 에서 각 step 이 끝났을 때,
# 성공 여부에 대해서 텔레그램으로 알럿을 받아볼 수 있도록 작성 중이다.
on:
  workflow_call:
    outputs:
      workflow_output1:
        description: "Build-Push Alert"
        value: ${{ jobs.my_job.outputs.job_output1 }}
      workflow_output2:
        description: "Deploy Alert"
        value: ${{ jobs.my_job.outputs.job_output2 }}

jobs:
  Build-Push-Alert:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}

    steps:
      - name: Failed
        id: step1
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'unassigned' }}
        run: echo "test=hello" >> "$GITHUB_OUTPUT"

      - name: Success
        id: step2
        if:
        run: echo "test=world" >> "$GITHUB_OUTPUT"

  Deploy:
    runs-on: ubuntu-latest
    needs: Build-Push-Alert
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"